### ISSUE TITLE
Distribution of preTrained models

### ISSUE THREAD

**Issue by Aakash-kaushik** [mlpack/models#66]
Creating an issue to discuss how to distribute pretrained model files. 
cc: @rcurtin 

gdrive link for resnet models: https://drive.google.com/drive/folders/15qqEhZnylW6OTk7HYrwOWiXzTiAK8-h6?usp=sharing

**Comment by rcurtin** [comment]
We'll need to modify the website build scripts just a little bit.  I think this should probably be separate from the `datasets/` directory.  (For that, the workflow when building the website is just that we get a file `datasets.tar.gz`, which is hosted locally under a different domain name on `mlpack.org`, as well as on Zenodo, and unpack it.)  I guess we can do the same thing here... just make a `models.tar.gz` that we maintain somewhere (not sure where?  I guess we could use Zenodo again?), and then host it 'locally' under a different subdomain.

Another idea could just be to make a separate subdomain `models.mlpack.org`, which is just a static subdomain that we (manually) dump files into.  In fact, we could even do the same thing for the datasets.

Any thoughts or preferences on how to do it?  Honestly I am leaning a little bit towards the `models.mlpack.org` strategy---and even adapting the datasets scripts to live in `datasets.mlpack.org/` (and thus simplifying the website rebuild process).

@Aakash-kaushik so that you can continue development work, for now I'm just putting the gdrive models in https://www.ratml.org/misc/models/.  Once we figure out what to do here, we can then just change the URL in the code accordingly.

(CC: @zoq since you've been pretty involved with the dataset setup)

**Comment by Aakash-kaushik** [comment]
@rcurtin i also lean more towards the idea of hosting static sites rather than having the whole process of expanding zips everytime we build the sites, also doesn't makes sense. 
As you said we can have a simple place where we can just dump files. And if you want just create one which can maybe have directories as url paths? 
Say `mlpack.org/datasets` and similar for models ?

**Comment by Aakash-kaushik** [comment]
> (The models are still uploading... it will be done in probably an hour or so...)

Thanks for uploading the models for time being

**Comment by rcurtin** [comment]
Yeah, I wonder why I didn't use a subdomain in the first place...

It would be way easier to set up `models.mlpack.org/` as opposed to `mlpack.org/models/`, since all of `mlpack.org/` will be rebuilt every night and I'd need to make sure that the `models/` URL correctly forwarded.  So unless there is some reason not to that I overlooked, I think it would fine to host as, e.g., `models.mlpack.org/resnet/resnet34.bin`.

**Comment by Aakash-kaushik** [comment]
I believe `models.mlpack.org` would be a better choice then.

**Comment by Aakash-kaushik** [comment]
Hey @rcurtin let me know when we have a final place where we put the models, that way I would update the current code to account for the change.

**Comment by rcurtin** [comment]
Done: http://models.mlpack.org/resnet/

The datasets still need to be changed though.  I guess that is not relevant to this issue though, so we can close this one.  Let me know if there is more I should add to that subdomain. :+1:

**Comment by Aakash-kaushik** [comment]
> Done: http://models.mlpack.org/resnet/
> 
> The datasets still need to be changed though. I guess that is not relevant to this issue though, so we can close this one. Let me know if there is more I should add to that subdomain.

Thank you so much ! :tada:
